export const OAUTH_TOKEN_SECRET_ID_ENV_NAME = 'OAUTH_TOKEN_SECRET_ID';
export const ACCESS_TOKEN_ENDPOINT_ENV_NAME = 'ACCESS_TOKEN_ENDPOINT';
export const WORDPRESS_API_BASE_ENV_VAR = 'WORDPRESS_API_BASE';